### ISSUE TITLE
changing scheduler

### ISSUE THREAD

**Issue by matthewygf** [sanposhiho/kube-scheduler-simulator-cli#1]
Hi thanks for the great work !

I have a question on changing the scheduler.

IIUC, you pull kubernetes into the submodules folder, and "scheduler.go" file just create a new instance of that scheduler.

Therefore, if I have a custom scheduler, I can also pull my pkg under submodules, and in my scheduler.go, I will create a new instance of my scheduler ?

Thanks !

**Comment by sanposhiho** [comment]
Hi. 

> I have a question on changing the scheduler.
IIUC, you pull kubernetes into the submodules folder, and "scheduler.go" file just create a new instance of that scheduler.
Therefore, if I have a custom scheduler, I can also pull my pkg under submodules, and in my scheduler.go, I will create a new instance of my scheduler ?

Depends on your custom scheduler, but, in most case, it's yes. 

If your custom scheduler is created from kubernetes/kubernetes repo, as you say, pulling your kubernetes repo that contains your custom scheduler should be fine.
And if you created custom-scheduler just to use your custom plugins, you don't need to pull your custom plugins. You can use custom-plugins by importing your custom plugins and passing these plugins via options here.
https://github.com/sanposhiho/kube-scheduler-simulator-cli/blob/master/scheduler/scheduler.go#L74-L79

**Comment by matthewygf** [comment]
Make sense, thanks a lot for the clarification.
